server:
  port: 7070
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-stacktrace: never
spring:
  #  profiles:
  #    active: local
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    static-path-pattern: /resources/**
  application:
    name: svc-project-web-bff
  
  http:
      encoding:
         charset : UTF-8
         enabled : true
         force : true
  

feign:
  customer-api:
    url: http://localhost:8181/
  store-api:
    url: http://localhost:8182/
  order-api:
    url: http://localhost:8183/